# -*- coding: utf-8 -*-
"""EntregaFinal_Despliegue.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e7ZqeO4Ag0DZC70B0B268ZwAEMLFdJh9

# Despliegue

- Cargamos el modelo
- Cargamos los datos futuros
- Preparar los datos futuros
- Aplicamos el modelo para la predicción
"""

#Cargamos librerías principales

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Cargamos el modelo
import pickle
filename = 'modelo-ensamble-reg-loads.pkl'
modelo, variables, min_max_scaler = pickle.load(open(filename, 'rb'))

# #Cargamos los datos futuros
# data = pd.read_csv("Predicciones.csv")
# data.head()

#Interfaz gráfica


#Se crea interfaz gráfica con streamlit para captura de los datos

import streamlit as st

st.set_page_config(page_title='Predicción de Cargas', page_icon='⛏️', layout='wide')

st.title('⛏️ Predicción de Cargas — Complex')
st.markdown('Ajusta los parámetros operacionales para obtener la predicción del modelo de ensamble.')
st.divider()

# --- Sección 1: Disponibilidad de equipos ---
st.subheader('Uso de Disponibilidad por Equipo')
st.caption('Valores normalizados entre 0.0 y 1.0')

cols = st.columns(5)
equipos = [
    '6231','6232','6233','6234','6235',
    '6236','6237','6238','6239','6241',
    '6242','6243','6244','6245','6246',
    '6247','6248','6249','6250','6260',
    '6261','6262','6263','6264','6268',
    '6269','6449','6455','6457'
]
valores = {}
for i, eq in enumerate(equipos):
    with cols[i % 5]:
        valores[eq] = st.number_input(
            f'Equipo {eq}',
            min_value=0.0, max_value=1.0,
            value=0.0, step=0.01,
            format='%.2f',
            key=f'eq_{eq}'
        )

st.divider()

# --- Sección 2: Parámetros de camiones ---
st.subheader('Parámetros Operacionales de Camiones')
col1, col2, col3 = st.columns(3)

with col1:
    Tks_Availability_OB = st.number_input(
        'Disponibilidad de camiones (OB)',
        min_value=0.0, max_value=1.0,
        value=0.0, step=0.01, format='%.2f'
    )
with col2:
    Tks_Utilization_OB = st.number_input(
        'Tiempo utilizado de camiones',
        min_value=0.0, max_value=1.0,
        value=0.0, step=0.01, format='%.2f'
    )
with col3:
    Cycle = st.number_input(
        'Tiempo de ciclo OB (min)',
        min_value=20.0, max_value=42.0,
        value=20.0, step=0.1, format='%.1f'
    )

st.divider()

# --- Sección 3: Turno ---
st.subheader('Turno')
Shift = st.radio('Selecciona el turno', ['D', 'N'], horizontal=True,
                 format_func=lambda x: '☀️ Diurno' if x == 'D' else '🌙 Nocturno')

st.divider()

# --- DataFrame ---
datos = [[
    valores['6231'], valores['6232'], valores['6233'], valores['6234'], valores['6235'],
    valores['6236'], valores['6237'], valores['6238'], valores['6239'], valores['6241'],
    valores['6242'], valores['6243'], valores['6244'], valores['6245'], valores['6246'],
    valores['6247'], valores['6248'], valores['6249'], valores['6250'], valores['6260'],
    valores['6261'], valores['6262'], valores['6263'], valores['6264'], valores['6268'],
    valores['6269'], valores['6449'], valores['6455'], valores['6457'],
    Tks_Availability_OB, Tks_Utilization_OB, Cycle, Shift
]]

data = pd.DataFrame(datos, columns=[
    'UsodeDisp_6231','UsodeDisp_6232','UsodeDisp_6233','UsodeDisp_6234','UsodeDisp_6235',
    'UsodeDisp_6236','UsodeDisp_6237','UsodeDisp_6238','UsodeDisp_6239','UsodeDisp_6241',
    'UsodeDisp_6242','UsodeDisp_6243','UsodeDisp_6244','UsodeDisp_6245','UsodeDisp_6246',
    'UsodeDisp_6247','UsodeDisp_6248','UsodeDisp_6249','UsodeDisp_6250','UsodeDisp_6260',
    'UsodeDisp_6261','UsodeDisp_6262','UsodeDisp_6263','UsodeDisp_6264','UsodeDisp_6268',
    'UsodeDisp_6269','UsodeDisp_6449','UsodeDisp_6455','UsodeDisp_6457',
    'Tks Availability OB','Tks Utilised Time','OB Cycle time (Min)','turno'
])
#Se realiza la preparación de datos
data_preparada=data.copy()

#En despliegue drop_first= False
data_preparada = pd.get_dummies(data_preparada, columns=['turno'], drop_first=False, dtype=int)
data_preparada.head()

#Se adicionan las columnas faltantes
data_preparada=data_preparada.reindex(columns=variables,fill_value=0)
data_preparada.head()

#Se normaliza la edad para predecir con Knn, Red, SVM
#En los despliegues no se llama fit
data_preparada[['UsodeDisp_6231','UsodeDisp_6232','UsodeDisp_6233','UsodeDisp_6234','UsodeDisp_6235','UsodeDisp_6236','UsodeDisp_6237','UsodeDisp_6238','UsodeDisp_6239','UsodeDisp_6241','UsodeDisp_6242','UsodeDisp_6243','UsodeDisp_6244','UsodeDisp_6245','UsodeDisp_6246','UsodeDisp_6247','UsodeDisp_6248','UsodeDisp_6249','UsodeDisp_6250','UsodeDisp_6260','UsodeDisp_6261','UsodeDisp_6262','UsodeDisp_6263','UsodeDisp_6264','UsodeDisp_6268','UsodeDisp_6269','UsodeDisp_6449','UsodeDisp_6455','UsodeDisp_6457','Tks Availability OB','Tks Utilised Time','OB Cycle time (Min)']]= min_max_scaler.transform(data_preparada[['UsodeDisp_6231','UsodeDisp_6232','UsodeDisp_6233','UsodeDisp_6234','UsodeDisp_6235','UsodeDisp_6236','UsodeDisp_6237','UsodeDisp_6238','UsodeDisp_6239','UsodeDisp_6241','UsodeDisp_6242','UsodeDisp_6243','UsodeDisp_6244','UsodeDisp_6245','UsodeDisp_6246','UsodeDisp_6247','UsodeDisp_6248','UsodeDisp_6249','UsodeDisp_6250','UsodeDisp_6260','UsodeDisp_6261','UsodeDisp_6262','UsodeDisp_6263','UsodeDisp_6264','UsodeDisp_6268','UsodeDisp_6269','UsodeDisp_6449','UsodeDisp_6455','UsodeDisp_6457','Tks Availability OB','Tks Utilised Time','OB Cycle time (Min)']])
data_preparada.head()

"""##**PREDICCIONES**"""

Y_pred = modelo.predict(data_preparada)

st.subheader('Resultado de la Predicción')
col_res1, col_res2 = st.columns([1, 2])
with col_res1:
    st.metric(label='Cargas estimadas', value=f'{int(round(Y_pred[0]))} cargas')
with col_res2:
    st.info('ℹ️ El modelo tiene un error aproximado del 1.5%')
